### ISSUE TITLE
StringBuilder

### ISSUE THREAD

**Issue by jrgs** [AW2122/DA_AW2122#3]
https://github.com/AW2122/DA_AW2122/blob/a3ce4d9334e75ca01163ffc5d83ad7927144ed0b/Unit02/Activity7_2_1/src/Program.java#L11

Did you need to use a StringBuilder? I don't think so

**Comment by AW2122** [comment]
When I was looking for information about the SAX parser I read that you
should avoid using a String, that using a StringBuilder is better. I have
only read it on one site though, so in the next exercise I used a String.
I'll look for the website and send you the link.

**Comment by jrgs** [comment]
StringBuilder class is designed to make (build) strings in a more efficient way. But, in your code, you are not building (by repetitively appending substrings) but just instantiating one time. So, in this case, the use of a StringBuilder is not necessary.
